[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://mere-hornet-nacif-2b03f653.koyeb.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200